;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,219,182

.instruments:
	.db $30 ;instrument $00
	.dw .env1,.env0,.env0
	.db $00
	.db $70 ;instrument $02
	.dw .env2,.env0,.env3
	.db $00
	.db $b0 ;instrument $03
	.dw .env2,.env0,.env3
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $cf,$cd,$cc,$ca,$c9,$c7,$c6,$c6,$c5,$c4,$c3,$c2,$c1,$02,$c0,$00
	.db $0e
.env2:
	.db $cf,$00,$00
.env3:
	.db $c0,$0c,$c1,$c2,$02,$c0,$be,$02,$c0,$c2,$00,$05


.song0ch0:
	.db $fb,$06
.song0ch0loop:
.ref0:
	.db $84,$33,$45,$41,$3d,$32,$87,$00,$32,$00,$33,$45,$41,$3d,$36,$8b
	.db $00
.ref1:
	.db $37,$47,$45,$41,$3a,$8d,$4a,$00,$4a,$00,$47,$41,$44,$8d
.ref2:
	.db $82,$33,$45,$41,$3d,$32,$87,$00,$32,$00,$33,$45,$41,$3d,$36,$8b
	.db $00
.ref3:
	.db $37,$47,$45,$41,$4a,$00,$4a,$00,$4a,$00,$4a,$00,$4f,$4b,$45,$41
	.db $3c,$85,$4a,$85
.ref4:
	.db $40,$00,$40,$00,$40,$83,$00,$40,$00,$40,$00,$40,$83,$00,$41,$47
	.db $3a,$83,$3c,$40,$8b,$00
.ref5:
	.db $44,$00,$44,$00,$45,$00,$44,$45,$40,$00,$40,$00,$40,$00,$40,$00
	.db $3c,$00,$3c,$00,$40,$00,$3c,$85,$4a,$85
	.db $ff,$16
	.dw .ref4
.ref7:
	.db $44,$00,$44,$00,$45,$00,$44,$44,$44,$40,$00,$40,$00,$40,$00,$46
	.db $00,$46,$00,$45,$40,$00,$36,$8d
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref8:
	.db $bf
.ref9:
	.db $bf
.ref10:
	.db $bf
.ref11:
	.db $bf
.ref12:
	.db $bf
.ref13:
	.db $bf
.ref14:
	.db $bf
.ref15:
	.db $bf
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref16:
	.db $bf
.ref17:
	.db $bf
.ref18:
	.db $bf
.ref19:
	.db $bf
.ref20:
	.db $bf
.ref21:
	.db $bf
.ref22:
	.db $bf
.ref23:
	.db $bf
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref24:
	.db $80,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a
	.db $85
.ref25:
	.db $1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85
	.db $ff,$10
	.dw .ref25
	.db $ff,$10
	.dw .ref25
	.db $ff,$10
	.dw .ref25
	.db $ff,$10
	.dw .ref25
	.db $ff,$10
	.dw .ref25
	.db $ff,$10
	.dw .ref25
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref32:
	.db $bf
.ref33:
	.db $bf
.ref34:
	.db $bf
.ref35:
	.db $bf
.ref36:
	.db $bf
.ref37:
	.db $bf
.ref38:
	.db $bf
.ref39:
	.db $bf
	.db $fd
	.dw .song0ch4loop
